CREATE TABLE CATEGORIES ( id INT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE PRODUCTS (id INT PRIMARY KEY, name TEXT NOT NULL);

INSERT INTO CATEGORIES VALUES 
(1, 'Gastronomic'),
(2, 'Book'),
(3, 'Telephone'),
(4, 'Laptop');

INSERT INTO PRODUCTS VALUES
(1, 'Cheese'),
(2, 'C# 9 and .NET 5 - Modern Cross-Platform Development, Fifth Edition'),
(3, 'Iphone 7'),
(4, 'Lenovo IdeaPad Gaming 3');

CREATE TABLE PRODUCTCATEGORY (
    PRODUCTId INT FOREIGN KEY REFERENCES PRODUCTS(id),
    CATEGORYId INT FOREIGN KEY REFERENCES CATEGORIES(id),
    PRIMARY KEY (PRODUCTId, CATEGORYId)
)

INSERT INTO PRODUCTCATEGORY VALUES
(1,1),
(2,2),
(3,3),
(4,4);

SELECT PRODUCT."name", CATEGORY."name" FROM PRODUCTS PRODUCT
LEFT JOIN PRODUCTCATEGORY PC
ON PRODUCT.id = PC.PRODUCTId
LEFT JOIN CATEGORIES CATEGORY
ON PC.CATEGORYId = CATEGORY.id